---
- name: Setup Airflow with Docker
  hosts: airflow
  become: yes
  tasks:
    - name: Install required packages
      dnf:
        name:
          - python3-pip
          - python3-devel
        state: present

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Check Docker version
      command: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Install Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: docker_version.rc != 0 or docker_version.stdout is version('20.10.0', '<')

    - name: Install Python requirements
      pip:
        name:
          - docker
          - requests
        state: present

    - name: Check docker-compose version
      command: docker-compose --version
      register: docker_compose_version
      ignore_errors: yes

    - name: Remove old docker-compose
      pip:
        name: docker-compose
        state: absent
      when: docker_compose_version.rc == 0 and docker_compose_version.stdout is version('2.22.0', '<')

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create Airflow directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ airflow_home }}/dags"
        - "{{ airflow_home }}/logs"
        - "{{ airflow_home }}/plugins"

    - name: Copy DAG files
      copy:
        src: "../files/dags/"
        dest: "{{ airflow_home }}/dags/"
        mode: '0644'

    - name: Start Airflow containers
      docker_compose:
        project_src: "{{ airflow_home }}"
        state: present