---
- name: Setup Airflow with Docker
  hosts: airflow
  become: yes
  tasks:
    - name: Install required packages
      dnf:
        name:
          - docker
          - python3-pip
          - python3-devel
        state: present

    - name: Install Python requirements
      pip:
        name:
          - docker
          - requests
        state: present

    - name: Remove old docker-compose
      pip:
        name: docker-compose
        state: absent

    - name: Download docker-compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create Airflow directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ airflow_home }}/dags"
        - "{{ airflow_home }}/logs"
        - "{{ airflow_home }}/plugins"

    - name: Copy DAG files
      copy:
        src: "../files/dags/"
        dest: "{{ airflow_home }}/dags/"
        mode: '0644'

    - name: Start Airflow containers
      docker_compose:
        project_src: "{{ airflow_home }}"
        state: present